### ISSUE TITLE
Make performance test results consistent

### ISSUE THREAD

**Issue by zyrolasting** [binpash/pash#108]
It's hard to tell what's going on in the performance test results.

* Some of the file names appear to have a relationship with `--width`, e.g. `wf_8_distr.time`, but then I see things like `wf_50_distr.time` or `p3b4_10_distr.time`.
* Underscores seem to play multiple roles in file names. If you split `wf_64_distr.time` by underscores, the test name is clearly the first element of the result. But in `web-index_p3_2gram_2_distr.time`, the test name is the first... 3 elements?
* Some files appear abandoned in version control. e.g. `_distr.time`, maybe some subdirectories?
* Some `*.time` files have more than just the output of `time`. They frequently have STDERR from `kill`, or messages like `Files ../evaluation//intermediary//wf_seq_output and /tmp/distr_output/0 are identical`.

I don't have a strong preference for the result format, but it would help if both the file names and contents were consistent.

**Comment by angelhof** [comment]
Thanks for these comments!

> Some of the file names appear to have a relationship with --width, e.g. wf_8_distr.time, but then I see things like wf_50_distr.time or p3b4_10_distr.time.

Some of these are very old files and results. I will delete them :)

> Underscores seem to play multiple roles in file names. If you split wf_64_distr.time by underscores, the test name is clearly the first element of the result. But in web-index_p3_2gram_2_distr.time, the test name is the first... 3 elements?

That's a good point, I guess from now on we can have a convention (for the old files I am parsing from the right).

> Some *.time files have more than just the output of time. They frequently have STDERR from kill, or messages like Files ../evaluation//intermediary//wf_seq_output and /tmp/distr_output/0 are identical.

This is a very good point. Actually all `.time` files have the pash logging information so that we can extract information from it. For example, PaSh outputs more fine grained time information (separated for compilation, optimization, execution, etc). Until know we have been using that information to plot performance results. Maybe from now on we can fix this to be slightly different, however I think that we might need pash logging information again. Do you have any ideas of how to solve this? Maybe we can just change the output file names to `.log` instead of `.time`?

**Comment by zyrolasting** [comment]
New bullet:

* `baseline_sort` has `_seq` and `_small_seq` variants whereas other datasets have only `_seq`.
