### ISSUE TITLE
dgsh_tee cleanup issue

### ISSUE THREAD

**Issue by dkarnikis** [binpash/pash#273]
Executing pash with `--dgsh_tee` flag generates big files (0.5G-1.6G) on /tmp that are not removed after script completion.
The generated filename format is something like `sg-g0FOvGgoyVkI`.
Changing the width number affects the number of the generated files.

- -w 8: 7 files
- -w 4: 3 files
- -w 2: 1 file

executing 1.sh from analytics-mts will trigger this 'bug'
$PASH_TOP/pa.sh  --dgsh_tee -w 2 1.sh

Commit: 6e149033484d00046869386538e6975176304873
Kernel: Linux livestar 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64 GNU/Linux
OS: Debian GNU/Linux 9 (stretch)
Machine: Livestar

**Comment by nvasilakis** [comment]
CC @angelhof @tammam1998

**Comment by nvasilakis** [comment]
(BTW congrats @dkarnikis, this is a great bug report, we should tag it and use it in the documentation as the model but report for newcomers)

**Comment by angelhof** [comment]
Thanks for the report! Are the files removed when execution completes successfully? Or do they always stay there?

@tammam1998 do you know if there is a flag that ensures that `dgsh-tee` removes intermediate files?

**Comment by nvasilakis** [comment]
> Thanks for the report! Are the files removed when execution completes successfully? Or do they always stay there?

Yes!

**Comment by tammam1998** [comment]
Hi @dkarnikis @nvasilakis  @angelhof 

I made a change to fix the problem in the dgsh fork we are using. Here is a [direct link to the commit](https://github.com/tammam1998/dgsh/commit/83f817fed23445c59405b250774efde3bec7ba72) for quick reference.

I tested it briefly and it looked like the bug was fixed with no side effects. Let me know if the issue persists in other test cases/situations or if anything breaks.

P.S you need to delete the dgsh-tee binary and run make.

**Comment by tammam1998** [comment]
@angelhof I don't believe there is such flag. All flags are documented [here](https://www2.dmst.aueb.gr/dds/sw/dgsh/dgsh-tee.html)

**Comment by angelhof** [comment]
Thanks @tammam1998 ! If this is indeed a bug in `dgst-tee` then we need to contact the authors. I am also a little concerned because I see this comment in the file https://github.com/tammam1998/dgsh/blob/pash/core-tools/src/dgsh-tee.c#L280.

I think that it is OK for now to use your solution (if `compiler/test_evaluation_scripts.sh --experimental` passes), but I think that we need to contact the authors of `dgst-tee` using a PR, explaining this issue and the fix :)

Tammam, whenever you have time can you make a PR in the `dgsh` repo with your fix? You can point to this issue here to give them more context

**Comment by tammam1998** [comment]
@angelhof will do!

**Comment by dkarnikis** [comment]
@tammam1998 I can verify that your fixes solve the issue. Thanks !
