### ISSUE TITLE
Only parallelize certain commands when they receive multiple inputs

### ISSUE THREAD

**Issue by khushikukadia** [binpash/pash#299]
For a command like tail, it wouldn't make sense to parallelize it on a single stream because the single file would split and yield an incorrect result. To optimize efficiency and maintain correctness, PaSh should only parallelize certain commands (ones that take multiple file arguments like wc -l*.txt and grep 'pizza' -ic*.txt) when multiple inputs are passed.

**Comment by angelhof** [comment]
I think that PaSh would only parallelize `tail` with the correct aggregator (that would make sure to do that properly. Similarly, it can correctly handle commands like `grep` and `wc` with a single input file argument as long as it has the correct aggregator.

I am not sure I understand the issue correctly, but if not, let me know and I can reopen this issue :) 

Also, all annotations (that determine how PaSh parallelizes commands) have been moved to https://github.com/binpash/annotations so maybe this issue is better to be moved there.
