### ISSUE TITLE
Create proper packages for python components

### ISSUE THREAD

**Issue by KOLANICH** [binpash/pash#332]

**Comment by dkarnikis** [comment]
Hello @KOLANICH.  
Could you elaborate more on the problem?
Thank you

**Comment by KOLANICH** [comment]
Not really a problem, but I just wonder if the tool can be teared into libs having use outside of this project. I.e. one of my long-lasting wishes (probably a rotten one already, in fact the last time I have tried to attack the problem was about a decade ago) is an automatic tool for transforming bash-oriented stuff (scripts for autotools, makefiles) into proper scripts in CMake and python. A parser for bash scripts can be useful for that.

**Comment by angelhof** [comment]
That would indeed be very nice to have, and it is in our longer term plans to "modularize" the project into separate components :)

Regarding parsing, PaSh builds on the [dash parser](https://github.com/mgree/libdash). Initially we were using the ocaml bindings but now we have python bindings. However note that the dash parser cannot parse full fledged bash scripts since bash has additional syntax.

**Comment by KOLANICH** [comment]
Thanks for the info.

**Comment by angelhof** [comment]
Thanks for the suggestion! I will close this issue for now (since we are very low on resources right now to pursue such a modularization).
