### ISSUE TITLE
pexpect dependency not automatically satisfied

### ISSUE THREAD

**Issue by mgree** [binpash/pash#471]
```ShellSession
; ./pa.sh
/Users/mgree/pash/compiler/pash_init_setup.sh: line 2: /Users/mgree/.pash_init: No such file or directory
Traceback (most recent call last):
  File "/Users/mgree/pash/compiler/pash_runtime_daemon.py", line 2, in <module>
    import pexpect
ModuleNotFoundError: No module named 'pexpect'
Error: Maximum retries: 100 exceeded when waiting for daemon to bind to socket!
Exiting...
```

Worse still, on my venerable 2014 MBP installing pexpect isn't enough for thing to work.

**Comment by dkarnikis** [comment]
Hello @mgree 
In the last updates, pash looks for all the needed python packages in a folder called `python_pkgs` in the root of the repo 
(that's why `pip install pexpect` does not solve your issue).
If I am not mistaken, you could try re-running the whole installation process (in case you are missing more deps):
```sh
sudo script/install-deps.sh 
bash scripts/setup.sh
``` 
OR 

you could only run `bash scripts/setup.sh` to reinstall the missing python packages.

**Comment by mgree** [comment]
Unfortunately, `install-deps.sh` refuses to run on my janky old MacBook Pro... 😅

**Comment by dkarnikis** [comment]
This makes sense. 
I think the script automatically exits when running on Darwin :/

**Comment by mgree** [comment]
Yes, Konstantinos and I just laughed when it happened. 😂 

But it would be good to use existing installed dependencies rather than vendoring them. Probably not a high priority thing, though.

**Comment by gulkily** [comment]
I'm having a similar issue on Manjaro. I've run both `pip install pexpect` and `pacman -S python-pexpect`.

**Comment by angelhof** [comment]
> I'm having a similar issue on Manjaro. I've run both `pip install pexpect` and `pacman -S python-pexpect`.

This is because of what @dkarnikis mentioned above (also see https://github.com/binpash/pash/blob/main/scripts/setup-pash.sh#L95). The way to go would be to run `setup-pash.sh`. If it doesn't run, then you could try selectively running lines 25-29 and lines 95-104. The reason is that PaSh looks for its internally needed imports (pexpect, jsonpickle) in a specific directory to minimize startup costs.

**Comment by mgree** [comment]
@angelhof explained the code vendoring as pretty important for startup costs.

Longer term, it would be ideal to precomput where Python packages live---that way we can avoid vendoring the libraries into the pash directory and let people install things in platform-specific ways. I'm not certain how complex this process is. Is Python just using a search path or something else? Would symlinks to system installations suffice? Is there some virtualenv trick to be played here?

**Comment by nvasilakis** [comment]
PR [581](https://github.com/binpash/pash/pull/581) fixes this. It has been tested on Fedora 36, Ubuntu 22.04 LTS, and Debian GNU/Linux 11 (bullseye).
