### ISSUE TITLE
Docker Push Action Failure

### ISSUE THREAD

**Issue by angelhof** [binpash/pash#544]
I am not sure how to address this: https://github.com/binpash/pash/actions/runs/2229959382

The automated workflow that pushes images to docker.io didn't seem to work.

**Comment by dkarnikis** [comment]
The issue should be fixed now :) 
I had probably misstyped the dockerhub account username on the repo settings.

Apart from the docker.io images, there are also the [github docker images](https://github.com/orgs/binpash/packages?repo_name=pash) that are identical to the docker.io, just being hosted on a different registry (they can be found below the releases tab on the main repo).

Moreover, should we remove [this](https://github.com/binpash/pash/pkgs/container/pash%2Fpash) outdated image on github registry? It hasn't being updated since last year. 

Next time there is an bug with CI or something similar, do not hesitate to tag me on the issue/PR!

**Comment by angelhof** [comment]
Thanks a lot @dkarnikis! I will tag you if I can't find the solution on my own but do it on your own time. There is no rush :)

Regarding the outdated image, I would prefer having a single default image that is called pash (and is the one visible on top that the people should use by default). No need to actually even publish the fedora and debian images on ghcr. Would that create any issue? Does anyone depend on those packages? If not, I will make a PR to fix it.

**Comment by angelhof** [comment]
PR #546 modifies the workflow to push a single image on github (and updates the version). If that looks OK, I will merge it and then delete the distro-named images from Github packages.
