### ISSUE TITLE
Improve IR formatting

### ISSUE THREAD

**Issue by angelhof** [binpash/pash#74]
At the moment, we format the IR back to a shell script (and arguments to strings) using custom procedures (e.g. `format_arg_char` in `ir_utils.py`). We need to make all this formatting using the libdash unparser.

The `impl.py` can also be improved to use it instead of producing a string itself.

Note: Since we need to call libdash parsers/unparsers often it might make sense to reimplement python bindings to the dash parser. This has the following benefits:
1. It might improve performance (since we wouldn't have to `exec` everytime we call the parser)
2. It will reduce our dependency to JSON
3. It will completely remove the dependency to ocaml (see #73)

**Comment by thurstond** [comment]
The C portion of the libdash library doesn't actually have an unparser; the unparser is written entirely in OCaml (JSON -> libdash OCaml AST -> shell script). If we want to eliminate both JSON and OCaml, then there is no "libdash unparser" that we can use.

The closest thing to a non-OCaml libdash unparser is the freshly minted ast2shell.py (https://github.com/andromeda/pash/blob/ceda/compiler/parser/ceda/ast2shell.py), whereby I've ported/modified the to_string function in ast.ml, to:

1. be written in pure Python instead of OCaml
2. serialize directly from the Pash AST to shell script

Compare to the to_string function of ast.ml, which goes from libdash OCaml AST -> shell script: https://github.com/angelhof/libdash/blob/ef6302502b904e33dd4cc686d71142fb1a87bbbd/ocaml/ast.ml

Konstantinos' comment above about AST vs. IR still holds; ast2shell.py is designed for the Pash AST.

**Comment by angelhof** [comment]
That's great!
